/**
 * Admin Panel UI Tests
 * 
 * Coverage for Epic 7 - Administration (UI)
 * Tests Admin Panel LLM tab, Agents tab, Logs tab
 * 
 * Generated by TEA (Murat) - Test Automation Workflow
 */

import { test, expect } from '@playwright/test';

test.describe('Admin Panel - LLM Tab', () => {
  
  test.beforeEach(async ({ page }) => {
    await page.goto('http://localhost:8000');
    await page.waitForLoadState('networkidle');
  });

  test('should open Admin panel', async ({ page }) => {
    // Click admin button or navigate to admin
    const adminButton = page.locator('[data-testid="admin-toggle"], #admin-toggle, .admin-button, button:has-text("Admin")');
    
    // Try to find and click the admin toggle
    const adminButtonExists = await adminButton.count() > 0;
    if (adminButtonExists) {
      await adminButton.click();
      await page.waitForTimeout(500);
    }
    
    // Check if admin panel is visible
    const adminPanel = page.locator('[data-testid="admin-panel"], #admin-panel, .admin-panel');
    await expect(adminPanel).toBeVisible();
  });

  test('LLM tab: should display provider selector', async ({ page }) => {
    // Navigate to admin panel first
    const adminButton = page.locator('[data-testid="admin-toggle"], #admin-toggle, .admin-button, button:has-text("Admin")');
    const adminButtonExists = await adminButton.count() > 0;
    if (adminButtonExists) {
      await adminButton.click();
    }
    
    // Click LLM tab
    const llmTab = page.locator('[data-testid="llm-tab"], #llm-tab, button:has-text("LLM")');
    if (await llmTab.count() > 0) {
      await llmTab.click();
      await page.waitForTimeout(300);
    }
    
    // Check for provider select
    const providerSelect = page.locator('[data-testid="llm-provider-select"], #llm-provider-select, select');
    // This test will FAIL if element doesn't exist - that's intentional
    await expect(providerSelect).toBeVisible();
  });

  test('LLM tab: should display model input', async ({ page }) => {
    const adminButton = page.locator('[data-testid="admin-toggle"], #admin-toggle, .admin-button, button:has-text("Admin")');
    if (await adminButton.count() > 0) {
      await adminButton.click();
    }
    
    const llmTab = page.locator('[data-testid="llm-tab"], #llm-tab, button:has-text("LLM")');
    if (await llmTab.count() > 0) {
      await llmTab.click();
    }
    
    const modelInput = page.locator('[data-testid="llm-model-input"], #llm-model-input, input[type="text"]');
    await expect(modelInput).toBeVisible();
  });

  test('LLM tab: should display base URL input', async ({ page }) => {
    const adminButton = page.locator('[data-testid="admin-toggle"], #admin-toggle, .admin-button, button:has-text("Admin")');
    if (await adminButton.count() > 0) {
      await adminButton.click();
    }
    
    const llmTab = page.locator('[data-testid="llm-tab"], #llm-tab, button:has-text("LLM")');
    if (await llmTab.count() > 0) {
      await llmTab.click();
    }
    
    const baseUrlInput = page.locator('[data-testid="llm-base-url-input"], #llm-base-url-input');
    await expect(baseUrlInput).toBeVisible();
  });

  test('LLM tab: should display Test Connection button', async ({ page }) => {
    const adminButton = page.locator('[data-testid="admin-toggle"], #admin-toggle, .admin-button, button:has-text("Admin")');
    if (await adminButton.count() > 0) {
      await adminButton.click();
    }
    
    const llmTab = page.locator('[data-testid="llm-tab"], #llm-tab, button:has-text("LLM")');
    if (await llmTab.count() > 0) {
      await llmTab.click();
    }
    
    const testBtn = page.locator('[data-testid="llm-test-btn"], #llm-test-btn, button:has-text("Test")');
    await expect(testBtn).toBeVisible();
  });
});

test.describe('Admin Panel - Agents Tab', () => {
  
  test.beforeEach(async ({ page }) => {
    await page.goto('http://localhost:8000');
    await page.waitForLoadState('networkidle');
  });

  test('Agents tab: should display agent cards container', async ({ page }) => {
    const adminButton = page.locator('[data-testid="admin-toggle"], #admin-toggle, .admin-button, button:has-text("Admin")');
    if (await adminButton.count() > 0) {
      await adminButton.click();
    }
    
    const agentsTab = page.locator('[data-testid="agents-tab"], #agents-tab, button:has-text("Agents")');
    if (await agentsTab.count() > 0) {
      await agentsTab.click();
      await page.waitForTimeout(300);
    }
    
    const agentCards = page.locator('[data-testid="agent-cards-container"], #agent-cards-container, .agent-cards');
    await expect(agentCards).toBeVisible();
  });

  test('Agents tab: should display agent LLM model input', async ({ page }) => {
    const adminButton = page.locator('[data-testid="admin-toggle"], #admin-toggle, .admin-button, button:has-text("Admin")');
    if (await adminButton.count() > 0) {
      await adminButton.click();
    }
    
    const agentsTab = page.locator('[data-testid="agents-tab"], #agents-tab, button:has-text("Agents")');
    if (await agentsTab.count() > 0) {
      await agentsTab.click();
    }
    
    const modelInput = page.locator('[data-testid="agent-llm-model"], #agent-llm-model');
    // At least one should exist if agents are present
    const count = await modelInput.count();
    expect(count).toBeGreaterThanOrEqual(0);
  });
});

test.describe('Admin Panel - Logs Tab', () => {
  
  test.beforeEach(async ({ page }) => {
    await page.goto('http://localhost:8000');
    await page.waitForLoadState('networkidle');
  });

  test('Logs tab: should display logs panel', async ({ page }) => {
    const adminButton = page.locator('[data-testid="admin-toggle"], #admin-toggle, .admin-button, button:has-text("Admin")');
    if (await adminButton.count() > 0) {
      await adminButton.click();
    }
    
    const logsTab = page.locator('[data-testid="logs-tab"], #logs-tab, button:has-text("Logs")');
    if (await logsTab.count() > 0) {
      await logsTab.click();
      await page.waitForTimeout(300);
    }
    
    const logsPanel = page.locator('[data-testid="logs-panel"], #logs-panel, .logs-panel');
    await expect(logsPanel).toBeVisible();
  });

  test('Logs tab: should display Pause button', async ({ page }) => {
    const adminButton = page.locator('[data-testid="admin-toggle"], #admin-toggle, .admin-button, button:has-text("Admin")');
    if (await adminButton.count() > 0) {
      await adminButton.click();
    }
    
    const logsTab = page.locator('[data-testid="logs-tab"], #logs-tab, button:has-text("Logs")');
    if (await logsTab.count() > 0) {
      await logsTab.click();
    }
    
    const pauseBtn = page.locator('[data-testid="pause-logs"], #pause-logs, button:has-text("Pause")');
    await expect(pauseBtn).toBeVisible();
  });

  test('Logs tab: should display Clear button', async ({ page }) => {
    const adminButton = page.locator('[data-testid="admin-toggle"], #admin-toggle, .admin-button, button:has-text("Admin")');
    if (await adminButton.count() > 0) {
      await adminButton.click();
    }
    
    const logsTab = page.locator('[data-testid="logs-tab"], #logs-tab, button:has-text("Logs")');
    if (await logsTab.count() > 0) {
      await logsTab.click();
    }
    
    const clearBtn = page.locator('[data-testid="clear-logs"], #clear-logs, button:has-text("Clear")');
    await expect(clearBtn).toBeVisible();
  });
});
