/**
 * Test Automation - UI Elements Complets
 * 
 * Tests pour: suggestion menu, log level, voice trigger, audio playback
 * 
 * Generated by TEA (Murat)
 */

import { test, expect } from '@playwright/test';

const BASE_URL = process.env.BASE_URL || 'http://localhost:8000';

// ============================================
// Suggestion Menu
// ============================================

test.describe('UI - Suggestion Menu', () => {
  
  test.beforeEach(async ({ page }) => {
    await page.goto('http://localhost:8000');
    await page.waitForLoadState('networkidle');
  });

  test('should show suggestion menu when typing', async ({ page }) => {
    const messageInput = page.locator('[data-testid="message-input"]');
    await messageInput.fill('/');
    
    await page.waitForTimeout(500);
    
    const menu = page.locator('[data-testid="suggestion-menu"], .suggestion-menu, .autocomplete');
    const count = await menu.count();
  });

  test('should filter suggestions based on input', async ({ page }) => {
    const messageInput = page.locator('[data-testid="message-input"]');
    await messageInput.fill('/i');
    
    await page.waitForTimeout(500);
    
    // Should show only matching suggestions
  });

  test('should select suggestion with keyboard', async ({ page }) => {
    const messageInput = page.locator('[data-testid="message-input"]');
    await messageInput.fill('/');
    await page.waitForTimeout(500);
    
    // Arrow down and enter
    await messageInput.press('ArrowDown');
    await messageInput.press('Enter');
    
    await page.waitForTimeout(500);
  });

  test('should close suggestion menu on escape', async ({ page }) => {
    const messageInput = page.locator('[data-testid="message-input"]');
    await messageInput.fill('/');
    await page.waitForTimeout(500);
    
    await messageInput.press('Escape');
    
    const menu = page.locator('[data-testid="suggestion-menu"]');
    // Should be hidden
  });
});

// ============================================
// Log Level Select
// ============================================

test.describe('UI - Log Level', () => {
  
  test.beforeEach(async ({ page }) => {
    await page.goto('http://localhost:8000');
    await page.waitForLoadState('networkidle');
  });

  test('should display log level selector', async ({ page }) => {
    const logSelect = page.locator('[data-testid="log-level-select"], #log-level, select');
    const count = await logSelect.count();
  });

  test('should change log level', async ({ page }) => {
    const logSelect = page.locator('[data-testid="log-level-select"], #log-level, select');
    if (await logSelect.count() > 0) {
      await logSelect.selectOption('debug');
    }
  });

  test('should persist log level preference', async ({ page }) => {
    const logSelect = page.locator('[data-testid="log-level-select"]');
    if (await logSelect.count() > 0) {
      await logSelect.selectOption('error');
      await page.reload();
      await page.waitForLoadState('networkidle');
      // Level should persist
    }
  });
});

// ============================================
// Voice Trigger Button
// ============================================

test.describe('UI - Voice Trigger', () => {
  
  test.beforeEach(async ({ page }) => {
    await page.goto('http://localhost:8000');
    await page.waitForLoadState('networkidle');
  });

  test('should show voice trigger button', async ({ page }) => {
    const voiceBtn = page.locator('[data-testid="voice-trigger"], #voice-trigger, button:has-text("🎤")');
    await expect(voiceBtn).toBeVisible();
  });

  test('should toggle voice listening mode', async ({ page }) => {
    const voiceBtn = page.locator('[data-testid="voice-trigger"]');
    if (await voiceBtn.count() > 0) {
      await voiceBtn.click();
      await page.waitForTimeout(1000);
      // Should show listening state
    }
  });

  test('should show voice indicator when listening', async ({ page }) => {
    const voiceBtn = page.locator('[data-testid="voice-trigger"]');
    if (await voiceBtn.count() > 0) {
      await voiceBtn.click();
      await page.waitForTimeout(500);
      
      const indicator = page.locator('[data-testid="voice-indicator"], .voice-listening');
    }
  });

  test('should stop listening on second click', async ({ page }) => {
    const voiceBtn = page.locator('[data-testid="voice-trigger"]');
    if (await voiceBtn.count() > 0) {
      await voiceBtn.click();
      await page.waitForTimeout(500);
      await voiceBtn.click();
      // Should stop listening
    }
  });
});

// ============================================
// Audio Playback
// ============================================

test.describe('UI - Audio Playback', () => {
  
  test.beforeEach(async ({ page }) => {
    await page.goto('http://localhost:8000');
    await page.waitForLoadState('networkidle');
  });

  test('should display audio player when agent responds with voice', async ({ page }) => {
    const messageInput = page.locator('[data-testid="message-input"]');
    await messageInput.fill('Say hello');
    await messageInput.press('Enter');
    
    await page.waitForTimeout(5000);
    
    const audioPlayer = page.locator('audio, [data-testid="audio-player"]');
  });

  test('should have play/pause button', async ({ page }) => {
    const playBtn = page.locator('[data-testid="play-button"], .play-pause');
    // May exist if audio is present
  });

  test('should show progress bar', async ({ page }) => {
    const progressBar = page.locator('[data-testid="audio-progress"], .audio-progress, input[type="range"]');
  });

  test('should show audio duration', async ({ page }) => {
    const duration = page.locator('[data-testid="audio-duration"], .duration');
  });

  test('should allow volume control', async ({ page }) => {
    const volumeControl = page.locator('[data-testid="volume-control"], .volume, input[type="range"]');
  });
});

// ============================================
// Additional UI Edge Cases
// ============================================

test.describe('UI - Additional Edge Cases', () => {
  
  test.beforeEach(async ({ page }) => {
    await page.goto('http://localhost:8000');
    await page.waitForLoadState('networkidle');
  });

  test('should handle slow network gracefully', async ({ page }) => {
    await page.route('**/*', route => route.continue());
    await page.reload();
    // Should show loading state
  });

  test('should show loading spinner', async ({ page }) => {
    const spinner = page.locator('[data-testid="loading"], .loading, .spinner');
  });

  test('should handle window resize', async ({ page }) => {
    await page.setViewportSize({ width: 375, height: 667 }); // Mobile
    await page.waitForTimeout(500);
    
    await page.setViewportSize({ width: 1920, height: 1080 }); // Desktop
  });

  test('should preserve state on resize', async ({ page }) => {
    const messageInput = page.locator('[data-testid="message-input"]');
    await messageInput.fill('Test message');
    
    await page.setViewportSize({ width: 375, height: 667 });
    await page.waitForTimeout(500);
    
    // Message should still be in input
  });
});
