/**
 * Admin Panel API Tests
 * 
 * Coverage for Epic 7 - Administration
 * P0: Token Usage, Agent Enable/Disable
 * 
 * Generated by TEA (Murat) - Test Automation Workflow
 */

import { test, expect } from '../support/fixtures/index';

const BASE_URL = process.env.BASE_URL || 'http://localhost:8000';

test.describe('Admin Panel API - Token Usage', () => {
  
  test('GET /api/admin/token-usage should return token usage data', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/admin/token-usage`);
    
    // Should return 200 OK
    expect(response.status()).toBe(200);
    
    // Should return an array
    const body = await response.json();
    expect(Array.isArray(body)).toBe(true);
    
    // If there are usage records, validate structure
    if (body.length > 0) {
      const firstRecord = body[0];
      // Check for expected fields (token usage record)
      expect(firstRecord).toHaveProperty('agent_id');
      expect(firstRecord).toHaveProperty('tokens');
    }
  });

  test('GET /api/admin/token-usage with agent_id filter', async ({ request }) => {
    const agentId = 'test-agent';
    const response = await request.get(`${BASE_URL}/api/admin/token-usage?agent_id=${agentId}`);
    
    expect(response.status()).toBe(200);
    
    const body = await response.json();
    expect(Array.isArray(body)).toBe(true);
    
    // All records should be for the specified agent
    body.forEach((record: any) => {
      expect(record.agent_id).toBe(agentId);
    });
  });

  test('GET /api/admin/token-usage with limit parameter', async ({ request }) => {
    const limit = 5;
    const response = await request.get(`${BASE_URL}/api/admin/token-usage?limit=${limit}`);
    
    expect(response.status()).toBe(200);
    
    const body = await response.json();
    expect(body.length).toBeLessThanOrEqual(limit);
  });
});

test.describe('Admin Panel API - Token Cost Summary', () => {
  
  test('GET /api/admin/token-cost-summary should return cost summary', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/admin/token-cost-summary`);
    
    expect(response.status()).toBe(200);
    
    const body = await response.json();
    expect(Array.isArray(body)).toBe(true);
  });

  test('GET /api/admin/token-cost-summary with date range', async ({ request }) => {
    const startDate = '2026-01-01';
    const endDate = '2026-01-31';
    const response = await request.get(
      `${BASE_URL}/api/admin/token-cost-summary?start_date=${startDate}&end_date=${endDate}`
    );
    
    expect(response.status()).toBe(200);
    
    const body = await response.json();
    expect(Array.isArray(body)).toBe(true);
  });
});

test.describe('Admin Panel API - Token Trends', () => {
  
  test('GET /api/admin/token-trends/daily', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/admin/token-trends/daily`);
    
    expect(response.status()).toBe(200);
    
    const body = await response.json();
    expect(Array.isArray(body)).toBe(true);
  });

  test('GET /api/admin/token-trends/daily with custom days', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/admin/token-trends/daily?days=7`);
    
    expect(response.status()).toBe(200);
    
    const body = await response.json();
    expect(Array.isArray(body)).toBe(true);
  });

  test('GET /api/admin/token-trends/weekly', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/admin/token-trends/weekly`);
    
    expect(response.status()).toBe(200);
    
    const body = await response.json();
    expect(Array.isArray(body)).toBe(true);
  });

  test('GET /api/admin/token-trends/monthly', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/admin/token-trends/monthly`);
    
    expect(response.status()).toBe(200);
    
    const body = await response.json();
    expect(Array.isArray(body)).toBe(true);
  });
});

test.describe('Admin Panel API - Agent Management', () => {
  
  test('GET /api/admin/agents should list all agents', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/admin/agents`);
    
    expect(response.status()).toBe(200);
    
    const body = await response.json();
    expect(Array.isArray(body)).toBe(true);
    
    // Each agent should have required fields
    if (body.length > 0) {
      const firstAgent = body[0];
      expect(firstAgent).toHaveProperty('agent_id');
      expect(firstAgent).toHaveProperty('is_active');
    }
  });

  test('GET /api/admin/agents/{agent_id}/status should return agent status', async ({ request }) => {
    // First get list of existing agents
    const listResponse = await request.get(`${BASE_URL}/api/admin/agents`);
    const agents = await listResponse.json();
    
    if (agents.length === 0) {
      // No agents available - skip this test
      test.skip();
      return;
    }
    
    // Use first available agent
    const agentId = agents[0].agent_id;
    const response = await request.get(`${BASE_URL}/api/admin/agents/${agentId}/status`);
    
    expect(response.status()).toBe(200);
    
    const body = await response.json();
    expect(body).toHaveProperty('agent_id');
    expect(body).toHaveProperty('is_active');
  });

  test('POST /api/admin/agents/{agent_id}/enable should enable agent', async ({ request }) => {
    const agentId = 'test-agent';
    const response = await request.post(`${BASE_URL}/api/admin/agents/${agentId}/enable`);
    
    expect(response.status()).toBe(200);
    
    const body = await response.json();
    expect(body).toHaveProperty('success');
  });

  test('POST /api/admin/agents/{agent_id}/disable should disable agent', async ({ request }) => {
    const agentId = 'test-agent';
    const response = await request.post(`${BASE_URL}/api/admin/agents/${agentId}/disable`);
    
    expect(response.status()).toBe(200);
    
    const body = await response.json();
    expect(body).toHaveProperty('success');
  });

  test('POST /api/admin/agents/{agent_id}/enable then disable should toggle agent', async ({ request }) => {
    const agentId = 'toggle-test-agent';
    
    // Enable
    const enableResponse = await request.post(`${BASE_URL}/api/admin/agents/${agentId}/enable`);
    expect(enableResponse.status()).toBe(200);
    
    // Disable
    const disableResponse = await request.post(`${BASE_URL}/api/admin/agents/${agentId}/disable`);
    expect(disableResponse.status()).toBe(200);
  });
});

test.describe('Admin Panel API - Error Handling', () => {
  
  test('GET /api/admin/agents/{invalid_agent_id}/status should handle unknown agent', async ({ request }) => {
    const agentId = 'nonexistent-agent-12345';
    const response = await request.get(`${BASE_URL}/api/admin/agents/${agentId}/status`);
    
    // Should return 200 or 404 depending on implementation
    expect([200, 404]).toContain(response.status());
  });

  test('GET /api/admin/token-usage with invalid limit should handle gracefully', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/admin/token-usage?limit=-1`);
    
    // Should handle invalid input gracefully
    expect([200, 400, 422]).toContain(response.status());
  });
});
