/**
 * Test Automation - COMPLETE API Tests
 * 
 * TOUS les tests API qui peuvent être écrits sans implémentation
 * Couvre: agents, history, admin complet, monitoring
 * 
 * Generated by TEA (Murat)
 */

import { test, expect } from '@playwright/test';

const BASE_URL = process.env.BASE_URL || 'http://localhost:8000';

// ============================================
// AGENTS API - 20 tests
// ============================================

test.describe('API - Agents - Complete', () => {
  
  test('GET /api/agents should return all agents', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/agents`);
    expect([200, 404, 501]).toContain(response.status());
  });

  test('GET /api/agents should include agent details', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/agents`);
    if (response.status() === 200) {
      const agents = await response.json();
      if (agents.length > 0) {
        expect(agents[0]).toHaveProperty('agent_id');
        expect(agents[0]).toHaveProperty('name');
      }
    }
  });

  test('GET /api/agents/{id} should return specific agent', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/agents/test-agent`);
    expect([200, 404, 501]).toContain(response.status());
  });

  test('GET /api/agents/{id}/status should return agent status', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/agents/test-agent/status`);
    expect([200, 404, 501]).toContain(response.status());
  });

  test('GET /api/agents/{id}/config should return config', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/agents/test-agent/config`);
    expect([200, 404, 501]).toContain(response.status());
  });

  test('PUT /api/agents/{id}/config should update config', async ({ request }) => {
    const response = await request.put(`${BASE_URL}/api/agents/test-agent/config`, {
      data: { settings: { key: 'value' } }
    });
    expect([200, 400, 404, 501]).toContain(response.status());
  });

  test('GET /api/agents/{id}/capabilities should return capabilities', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/agents/test-agent/capabilities`);
    expect([200, 404, 501]).toContain(response.status());
  });

  test('GET /api/agents/{id}/history should return history', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/agents/test-agent/history`);
    expect([200, 404, 501]).toContain(response.status());
  });

  test('GET /api/agents/online should return online agents', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/agents/online`);
    expect([200, 404, 501]).toContain(response.status());
  });

  test('GET /api/agents/{id}/presence should return presence', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/agents/test-agent/presence`);
    expect([200, 404, 501]).toContain(response.status());
  });

  test('GET /api/agents/{id}/emotion should return emotion', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/agents/test-agent/emotion`);
    expect([200, 404, 501]).toContain(response.status());
  });

  test('POST /api/agents should create new agent', async ({ request }) => {
    const response = await request.post(`${BASE_URL}/api/agents`, {
      data: { agent_id: 'new-agent', name: 'New Agent' }
    });
    expect([201, 400, 404, 501]).toContain(response.status());
  });

  test('DELETE /api/agents/{id} should delete agent', async ({ request }) => {
    const response = await request.delete(`${BASE_URL}/api/agents/test-agent`);
    expect([200, 204, 404, 501]).toContain(response.status());
  });

  test('GET /api/agents should filter by status', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/agents?status=online`);
    expect([200, 404, 501]).toContain(response.status());
  });

  test('GET /api/agents should filter by name', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/agents?name=renarde`);
    expect([200, 404, 501]).toContain(response.status());
  });

  test('GET /api/agents should support pagination', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/agents?page=1&limit=10`);
    expect([200, 404, 501]).toContain(response.status());
  });

  test('GET /api/agents should include metadata', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/agents?include_metadata=true`);
    expect([200, 404, 501]).toContain(response.status());
  });

  test('GET /api/agents/{id}/skills should return skills', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/agents/test-agent/skills`);
    expect([200, 404, 501]).toContain(response.status());
  });

  test('PUT /api/agents/{id}/skills should update skills', async ({ request }) => {
    const response = await request.put(`${BASE_URL}/api/agents/test-agent/skills`, {
      data: { skills: ['skill1', 'skill2'] }
    });
    expect([200, 400, 404, 501]).toContain(response.status());
  });

  test('GET /api/agents/{id}/persona should return persona', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/agents/test-agent/persona`);
    expect([200, 404, 501]).toContain(response.status());
  });
});

// ============================================
// HISTORY API - 15 tests
// ============================================

test.describe('API - History - Complete', () => {
  
  test('GET /api/history should return chat history', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/history`);
    expect([200, 404, 501]).toContain(response.status());
  });

  test('GET /api/history should filter by agent', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/history?agent_id=agent1`);
    expect([200, 404, 501]).toContain(response.status());
  });

  test('GET /api/history should filter by user', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/history?user_id=user1`);
    expect([200, 404, 501]).toContain(response.status());
  });

  test('GET /api/history should filter by date range', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/history?from=2026-01-01&to=2026-01-31`);
    expect([200, 404, 501]).toContain(response.status());
  });

  test('GET /api/history should support pagination', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/history?page=1&limit=50`);
    expect([200, 404, 501]).toContain(response.status());
  });

  test('GET /api/history/{id} should return specific message', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/history/msg123`);
    expect([200, 404, 501]).toContain(response.status());
  });

  test('DELETE /api/history should clear history', async ({ request }) => {
    const response = await request.delete(`${BASE_URL}/api/history`);
    expect([200, 204, 404, 501]).toContain(response.status());
  });

  test('DELETE /api/history/{id} should delete specific message', async ({ request }) => {
    const response = await request.delete(`${BASE_URL}/api/history/msg123`);
    expect([200, 204, 404, 501]).toContain(response.status());
  });

  test('GET /api/history/search should search messages', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/history/search?q=hello`);
    expect([200, 404, 501]).toContain(response.status());
  });

  test('GET /api/history/export should export history', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/history/export?format=json`);
    expect([200, 404, 501]).toContain(response.status());
  });

  test('GET /api/history should sort by date', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/history?sort=desc`);
    expect([200, 404, 501]).toContain(response.status());
  });

  test('GET /api/history/agents/{id} should return agent history', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/history/agents/agent1`);
    expect([200, 404, 501]).toContain(response.status());
  });

  test('GET /api/history/statistics should return stats', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/history/statistics`);
    expect([200, 404, 501]).toContain(response.status());
  });

  test('PUT /api/history/{id} should update message', async ({ request }) => {
    const response = await request.put(`${BASE_URL}/api/history/msg123`, {
      data: { content: 'updated' }
    });
    expect([200, 400, 404, 501]).toContain(response.status());
  });

  test('GET /api/history/threads should return threads', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/history/threads`);
    expect([200, 404, 501]).toContain(response.status());
  });
});

// ============================================
// ADMIN API - 15 tests
// ============================================

test.describe('API - Admin - Complete', () => {
  
  test('GET /api/admin/system should return system info', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/admin/system`);
    expect([200, 404, 501]).toContain(response.status());
  });

  test('GET /api/admin/health should return health', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/admin/health`);
    expect([200, 404, 501]).toContain(response.status());
  });

  test('GET /api/admin/metrics should return metrics', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/admin/metrics`);
    expect([200, 404, 501]).toContain(response.status());
  });

  test('GET /api/admin/config should return config', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/admin/config`);
    expect([200, 404, 501]).toContain(response.status());
  });

  test('PUT /api/admin/config should update config', async ({ request }) => {
    const response = await request.put(`${BASE_URL}/api/admin/config`, {
      data: { key: 'value' }
    });
    expect([200, 400, 404, 501]).toContain(response.status());
  });

  test('GET /api/admin/logs should return logs', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/admin/logs`);
    expect([200, 404, 501]).toContain(response.status());
  });

  test('GET /api/admin/logs should filter by level', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/admin/logs?level=error`);
    expect([200, 404, 501]).toContain(response.status());
  });

  test('POST /api/admin/backup should create backup', async ({ request }) => {
    const response = await request.post(`${BASE_URL}/api/admin/backup`);
    expect([200, 201, 404, 501]).toContain(response.status());
  });

  test('POST /api/admin/restore should restore backup', async ({ request }) => {
    const response = await request.post(`${BASE_URL}/api/admin/restore`, {
      data: { backup_id: 'backup123' }
    });
    expect([200, 400, 404, 501]).toContain(response.status());
  });

  test('GET /api/admin/backups should list backups', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/admin/backups`);
    expect([200, 404, 501]).toContain(response.status());
  });

  test('DELETE /api/admin/backups/{id} should delete backup', async ({ request }) => {
    const response = await request.delete(`${BASE_URL}/api/admin/backups/backup123`);
    expect([200, 204, 404, 501]).toContain(response.status());
  });

  test('GET /api/admin/users should list users', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/admin/users`);
    expect([200, 404, 501]).toContain(response.status());
  });

  test('GET /api/admin/stats should return stats', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/admin/stats`);
    expect([200, 404, 501]).toContain(response.status());
  });

  test('POST /api/admin/maintenance should start maintenance', async ({ request }) => {
    const response = await request.post(`${BASE_URL}/api/admin/maintenance`, {
      data: { action: 'start' }
    });
    expect([200, 400, 404, 501]).toContain(response.status());
  });

  test('GET /api/admin/versions should return versions', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/admin/versions`);
    expect([200, 404, 501]).toContain(response.status());
  });
});

// ============================================
// MONITORING API - 10 tests
// ============================================

test.describe('API - Monitoring - Complete', () => {
  
  test('GET /api/metrics should return metrics', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/metrics`);
    expect([200, 404, 501]).toContain(response.status());
  });

  test('GET /api/metrics/agents should return agent metrics', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/metrics/agents`);
    expect([200, 404, 501]).toContain(response.status());
  });

  test('GET /api/metrics/system should return system metrics', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/metrics/system`);
    expect([200, 404, 501]).toContain(response.status());
  });

  test('GET /api/metrics/performance should return performance', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/metrics/performance`);
    expect([200, 404, 501]).toContain(response.status());
  });

  test('GET /api/debug should return debug info', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/debug`);
    expect([200, 404, 501]).toContain(response.status());
  });

  test('GET /api/debug/threads should return thread info', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/debug/threads`);
    expect([200, 404, 501]).toContain(response.status());
  });

  test('GET /api/debug/memory should return memory info', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/debug/memory`);
    expect([200, 404, 501]).toContain(response.status());
  });

  test('POST /api/debug/gc should trigger garbage collection', async ({ request }) => {
    const response = await request.post(`${BASE_URL}/api/debug/gc`);
    expect([200, 404, 501]).toContain(response.status());
  });

  test('GET /api/health should return health check', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/health`);
    expect([200, 404, 501]).toContain(response.status());
  });

  test('GET /api/ready should return readiness', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/ready`);
    expect([200, 404, 501]).toContain(response.status());
  });
});

// ============================================
// ERROR HANDLING API - 10 tests
// ============================================

test.describe('API - Error Handling - Complete', () => {
  
  test('should return 404 for unknown endpoint', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/notfound`);
    expect([404, 501]).toContain(response.status());
  });

  test('should return 400 for invalid JSON', async ({ request }) => {
    const response = await request.post(`${BASE_URL}/api/agents`, {
      headers: { 'Content-Type': 'application/json' },
      data: 'invalid json'
    });
    expect([400, 422, 501]).toContain(response.status());
  });

  test('should return 400 for missing required field', async ({ request }) => {
    const response = await request.post(`${BASE_URL}/api/agents`, {
      data: { name: 'Test' } // missing agent_id
    });
    expect([400, 422, 501]).toContain(response.status());
  });

  test('should return 401 for unauthorized request', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/admin/private`);
    expect([401, 403, 404, 501]).toContain(response.status());
  });

  test('should return 429 for rate limiting', async ({ request }) => {
    const responses: number[] = [];
    for (let i = 0; i < 20; i++) {
      const response = await request.get(`${BASE_URL}/api/agents`);
      responses.push(response.status());
    }
    expect(responses.some(s => s === 429)).toBe(true);
  });

  test('should return 500 for server error', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/debug/error`);
    expect([500, 404, 501]).toContain(response.status());
  });

  test('should include error details in response', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/notfound`);
    const body = await response.json();
    expect(body).toHaveProperty('error');
  });

  test('should support custom error codes', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/agents/invalid!@#$`);
    expect([400, 404, 422, 501]).toContain(response.status());
  });

  test('should handle timeout gracefully', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/slow`, { timeout: 1000 });
    expect([408, 500, 504, 501]).toContain(response.status());
  });

  test('should validate query parameters', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/agents?limit=-1`);
    expect([400, 422, 501]).toContain(response.status());
  });
});
